#!/usr/bin/env bash
#a
#b
#c

hour=0

while [ $hour -le 12 ]
do 
        echo "Hour: $hour"
        minute=1
        while [ $minute -le 59 ]
        do
                echo "$minute"
        done
        (( hour++ ))
done
