#!/usr/bin/env bash
# alot
echo $$ > /var/run/myscript.pid
trap 'echo"Y U no love me?!"' 2
trap 'rm /var/run/myscript.pid' 3 15
while true;
do
    echo "To infinity and beyond"
    sleep 2
    echo "I hate the kill command"
done
