#!/usr/bin/env bash
#we are the o
#q
while true;
do
   /var/run/myscript.pid= "GO"
    echo $$ > $/var/run/myscript.pid
    echo "To infinity and beyond"
    echo "I hate the kill command"  
    echo "Y U no love me?!"
    rm /var/run/myscript.pid
done
