#!/usr/bin/env bash
#www
manage_my_process='/var/run/my_process.pid'
echo $$ /var/run/my_process.pid
	if [ -f $/var/run/my_process.pid]; then 
	       	manage_my_process
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
	
	elif [ -f $/var/run/my_process.pid ]; then 
		kill -L manage_my_process
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
	
	elif [ -f $/var/run/my_process.pid]; then 
		kill -L manage_my_process
		rm /var/run/my_process.pid
		manage_my_process
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted" 
        if
