#!/usr/bin/env bash
# I am alive
declare -a instruction=(
[0]=start
[1]=stop
[2]=restart
)
for i in ${instruction}
do
if [ i==0 ]; then
manage_my_process
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"
elif [ i==1 ]; then
kill -L manage_my_process
rm /var/run/my_process.pid
echo "manage_my_process stopped"
elif [ i==2 ]; then
kill -L manage_my_process
rm /var/run/my_process.pid
manage_my_process
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
done
