#!/usr/bin/env bash                                                            
# Best school 10 times using while loop                                     
kill "$(pgrep -f 4-to_infinity_and_beyond)"
